apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  interval: 30m
  chart:
    spec:
      chart: cilium
      version: "1.19.x"
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: flux-system
  values:
    kubeProxyReplacement: true
    k8sServiceHost: 192.168.86.54
    k8sServicePort: 6443
    ipam:
      operator:
        clusterPoolIPv4PodCIDRList:
          - "10.244.0.0/16"
    envoy:
      enabled: false
    operator:
      replicas: 1
