apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ngf
  namespace: nginx-gateway
spec:
  interval: 30m
  chart:
    spec:
      chart: nginx-gateway-fabric
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: nginx-gateway-fabric
        namespace: flux-system
  install:
    createNamespace: true
  dependsOn:
    - name: metallb
      namespace: metallb-system
